version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: aavash
      POSTGRES_PASSWORD: 'Aavash@33'
      POSTGRES_DB: form2
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    
  app1:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://aavash:Aavash@33@db:5432/form2
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge